shallow_clone: true
build: off
install:
  - npm i polymer-cli
  - npm i polymer
before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - pip install requests
  - chromedriver.exe --version
  - geckodriver.exe --version
  - IEDriverServer.exe --version
  - polymer --version