version: 1.0.{build}
environment:
  LAUNCHPAD_BROWSERS: chrome
cache: node_modules/
build_script:
- cmd: >-
    npm install -g polymer-cli

    npm i wct-browser-legacy

    polymer test --verbose